language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "QYAsj0sNlPKY/QuRAkupRb4pdQZBNTQ66kcHWrGs04eRrjAVwhBIN5gvpJTnJuLbxGNJePIDu7TjbcnaDyAXoQ5QVWlLZOHOUPinbzrFdMUjDWOPlJjHc00f2o9eDlGENKWKEI3NCLphqaKepOJ6oAvwooCGYkuftUeudEhNQ94="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
