language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "kGkszrQG6V6BAfwZmGAHRfaOHbn2o0hXuBfp8TutXtdc3dNFCy5ZVptJrTR3\nSQF4baDhRQDIBVWrIpbLiaLIVH/XxrstriGv5hfD7Mumun98/X2qXUOl0ku4\n69usbE9mfZ+z0yGsRti6Owt6Elz5qU+OsVpWgP5ZblT1K6OUACA="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install:        composer install --dev
script:         ./vendor/bin/travis-build
after_success:  ./vendor/bin/travis-success
